batch_size: 16
epoch: 200
learning_rate: 1e-3
gpu: 1
num_point: 1024
optimizer: Adam
weight_decay: 1e-4
normal: True
lr_decay: 0.5
step_size: 20

defaults:
  - model: Hengshuang

hydra:
  run:
    dir: log/partseg/${model.name}

  sweep:
    dir: log/partseg
    subdir: ${model.name}
